CREATE TABLE [dbo].[tbLembreteIoTDevice]
(
	[Id]			INT				NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[LembreteId]	INT				NOT NULL FOREIGN KEY REFERENCES dbo.tbLembrete(Id) ON DELETE CASCADE,
	[IoTDeviceId]	INT				NOT NULL FOREIGN KEY REFERENCES dbo.tbIotDevice(Id) ON DELETE CASCADE,
)
